### PR TITLE
Add README_EN.md

### PR DESCRIPTION
**Pull request by Tina66**
Add a file  README_EN.md.

### CODE REVIEW

**Comment by wangqing1218** [comment]
@zmzhouXJTU @throcean Can you review this PR?

**Comment by zmzhouXJTU** [comment]
OK , I will review it @wangqing1218

**Comment by zmzhouXJTU** [comment]
I have updated some small mistakes about the grammar of markdown. The others I think is OK . 
How I updated and what I have updated you can see in the log of "Commits" @wangqing1218 @Tina66

**Comment by Tina66** [comment]
Thanks!I have seen it.

**Comment by wangqing1218** [comment]
@zmzhouXJTU  OK. A reviewer shouldn't update any commit for this PR. The reviewer should comment the code only. Then the PRer corrects the code about the comments or re-comments for the comments.

**Comment by MrKingHH** [comment]
OK,well down!

**Comment by wangqing1218** [comment]
@Tina66 The commit message should be "1". Commit message should describe what the change is.

**Comment by Tina66** [comment]
should be 1?you mean  I shoud commit one message in one time?

**Pull request merged**
